### ISSUE TITLE
LOCAL VARIABLE 'x' REFRENCED BEFORE ASSIGNMENT

### ISSUE THREAD

**Issue by amit-iiitm** [zerodhatech/pdf_text_overlay#2]
While filling the pdf this error throws up, I think it is because some key-value pair is not provided while x and y coordinates are calculated for some fields.
Please help.

**Comment by shridarpatil** [comment]
fixed!

**Comment by shridarpatil** [comment]
@amit-iiitm this is fixed can you close the issue?

**Comment by amit-iiitm** [comment]
Thanks
